### Import Essentials

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cpu


### Creating Tensors

In [2]:
# MATRIX

MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [3]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [4]:
# No. of dimensions 

TENSOR.ndim

3

### Random Tensors

#### Why random tensors?

#### Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [5]:
# Creating a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0780, 0.8387, 0.1540, 0.4961],
        [0.1220, 0.4829, 0.0794, 0.6755],
        [0.5684, 0.4516, 0.9573, 0.8893]])

In [6]:
random_tensor.ndim

2

In [7]:
# Creating a random tensor with similar shape to an image tensor 

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [8]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [14]:
# Use torch.range()

one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
tensor_range = torch.arange(start=1, end=11, step=1)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])